### ISSUE TITLE
!c An error occurred generating ctags: /bin/bash: ag: command not found

### ISSUE THREAD

**Issue by xahon** [fntlnz/atags.vim#12]
After I call `atags#generate()` this error occurred

**Comment by cesargomez89** [comment]
install the silver searcher ...

**Comment by fntlnz** [comment]
@xahon atags really executes the list of commands you put in the `atags_build_commands_list` global variable. 
If you use the `ag` command then you will need it as @cesargomez89 is suggesting. Here you go: https://github.com/ggreer/the_silver_searcher
