### ISSUE TITLE
error opening neovim 

### ISSUE THREAD

**Issue by zackhsi** [fntlnz/atags.vim#5]
Let me preface this with sorry, this is a horrible vague issue. I'm running a release neovim build, which doesn't produce logs.

I get a "Error detected while processing [...] #generate:" when I open neovim without args (`nvim`). More text flashes afterwards, but it's too quick to see. There might be the string "command_list" and "on_stdout" somewhere.

If I open a file directly, I do not get an error.

**Comment by davidosomething** [comment]
use `:messages` to see what it said

**Comment by zackhsi** [comment]
Ah, brilliant! Here's a pr: https://github.com/fntlnz/atags.vim/pull/6.

I have this line in my vimrc:

``` viml
autocmd BufWritePost,BufEnter * call atags#generate()
```

Which causes:

```
Error detected while processing function atags#generate:
line    1:
E121: Undefined variable: g:atags_on_generate_stderr
E116: Invalid arguments for function function(g:atags_on_generate_stderr), 'on_stdout': function(g:at
ags_on_generate_stdout), 'on_exit': function(g:atags_on_generate_exit) }
E15: Invalid expression: { 'on_stderr': function(g:atags_on_generate_stderr), 'on_stdout': function(g
:atags_on_generate_stdout), 'on_exit': function(g:atags_on_generate_exit) }
line    7:
E121: Undefined variable: g:atags_build_commands_list
E116: Invalid arguments for function extend
line    8:
E121: Undefined variable: g:atags_build_commands_list
E116: Invalid arguments for function join(g:atags_build_commands_list, ";"), opts)
E116: Invalid arguments for function jobstart
```
